window.EMPLOYEES = [{
    "Id": 1,
    "FirstName": "John",
    "LastName": "Heart",
    "Prefix": "Mr.",
    "Title": "CEO",
    "City": "Los Angeles",
    "Phone": "(213) 555-9392",
    "Email": "jheart@dx-email.com",
    "BirthDate": "1964-03-16 00:00:00",
    "Department": "Management"
}, {
    "Id": 2,
    "FirstName": "Samantha",
    "LastName": "Bright",
    "Prefix": "Dr.",
    "Title": "COO",
    "City": "Los Angeles",
    "Phone": "(213) 555-2858",
    "Email": "samanthab@dx-email.com",
    "BirthDate": "1966-05-02 00:00:00",
    "Department": "Management"
}, {
    "Id": 3,
    "FirstName": "Arthur",
    "LastName": "Miller",
    "Prefix": "Mr.",
    "Title": "CTO",
    "City": "Los Angeles",
    "Phone": "(310) 555-8583",
    "Email": "arthurm@dx-email.com",
    "BirthDate": "1972-07-11 00:00:00",
    "Department": "Management"
}, {
    "Id": 4,
    "FirstName": "Robert",
    "LastName": "Reagan",
    "Prefix": "Mr.",
    "Title": "CMO",
    "City": "Pasadena",
    "Phone": "(818) 555-2387",
    "Email": "robertr@dx-email.com",
    "BirthDate": "1974-09-07 00:00:00",
    "Department": "Management"
}, {
    "Id": 5,
    "FirstName": "Greta",
    "LastName": "Sims",
    "Prefix": "Ms.",
    "Title": "HR Manager",
    "City": "Alhambra",
    "Phone": "(818) 555-6546",
    "Email": "gretas@dx-email.com",
    "BirthDate": "1977-11-22 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 6,
    "FirstName": "Brett",
    "LastName": "Wade",
    "Prefix": "Mr.",
    "Title": "IT Manager",
    "City": "San Marino",
    "Phone": "(626) 555-0358",
    "Email": "brettw@dx-email.com",
    "BirthDate": "1968-12-01 00:00:00",
    "Department": "IT"
}, {
    "Id": 7,
    "FirstName": "Sandra",
    "LastName": "Johnson",
    "Prefix": "Mrs.",
    "Title": "Controller",
    "City": "Long Beach",
    "Phone": "(562) 555-2082",
    "Email": "sandraj@dx-email.com",
    "BirthDate": "1974-11-15 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 8,
    "FirstName": "Edward",
    "LastName": "Holmes",
    "Prefix": "Dr.",
    "Title": "Sales Manager",
    "City": "Malibu",
    "Phone": "(310) 555-1288",
    "Email": "edwardh@dx-email.com",
    "BirthDate": "1973-07-14 00:00:00",
    "Department": "Sales"
}, {
    "Id": 9,
    "FirstName": "Barbara",
    "LastName": "Banks",
    "Prefix": "Mrs.",
    "Title": "Support Manager",
    "City": "Pacific Palisades",
    "Phone": "(310) 555-3355",
    "Email": "barbarab@dx-email.com",
    "BirthDate": "1979-04-14 00:00:00",
    "Department": "Support"
}, {
    "Id": 10,
    "FirstName": "Kevin",
    "LastName": "Carter",
    "Prefix": "Mr.",
    "Title": "Shipping Manager",
    "City": "Los Angeles",
    "Phone": "(213) 555-2840",
    "Email": "kevinc@dx-email.com",
    "BirthDate": "1978-01-09 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 11,
    "FirstName": "Cynthia",
    "LastName": "Stanwick",
    "Prefix": "Ms.",
    "Title": "HR Assistant",
    "City": "Glendale",
    "Phone": "(818) 555-6655",
    "Email": "cindys@dx-email.com",
    "BirthDate": "1985-06-05 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 12,
    "FirstName": "Sam",
    "LastName": "Hill",
    "Prefix": "Mr.",
    "Title": "Sales Assistant",
    "City": "Pasadena",
    "Phone": "(626) 555-7292",
    "Email": "sammyh@dx-email.com",
    "BirthDate": "1984-02-17 00:00:00",
    "Department": "Sales"
}, {
    "Id": 13,
    "FirstName": "David",
    "LastName": "Jones",
    "Prefix": "Mr.",
    "Title": "Shipping Assistant",
    "City": "Pasadena",
    "Phone": "(626) 555-0281",
    "Email": "davidj@dx-email.com",
    "BirthDate": "1983-03-06 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 14,
    "FirstName": "Victor",
    "LastName": "Norris",
    "Prefix": "Mr.",
    "Title": "Shipping Assistant",
    "City": "Los Angeles",
    "Phone": "(213) 555-9278",
    "Email": "victorn@dx-email.com",
    "BirthDate": "1986-07-23 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 15,
    "FirstName": "Mary",
    "LastName": "Stern",
    "Prefix": "Ms.",
    "Title": "Shipping Assistant",
    "City": "Glendale",
    "Phone": "(818) 555-7857",
    "Email": "marys@dx-email.com",
    "BirthDate": "1982-04-08 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 16,
    "FirstName": "Robin",
    "LastName": "Cosworth",
    "Prefix": "Mrs.",
    "Title": "Shipping Assistant",
    "City": "Los Angeles",
    "Phone": "(818) 555-0942",
    "Email": "robinc@dx-email.com",
    "BirthDate": "1981-06-12 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 17,
    "FirstName": "Kelly",
    "LastName": "Rodriguez",
    "Prefix": "Ms.",
    "Title": "Support Assistant",
    "City": "Glendale",
    "Phone": "(818) 555-9248",
    "Email": "kellyr@dx-email.com",
    "BirthDate": "1988-05-11 00:00:00",
    "Department": "Support"
}, {
    "Id": 18,
    "FirstName": "James",
    "LastName": "Anderson",
    "Prefix": "Mr.",
    "Title": "Support Assistant",
    "City": "Los Angeles",
    "Phone": "(323) 555-4702",
    "Email": "jamesa@dx-email.com",
    "BirthDate": "1987-01-29 00:00:00",
    "Department": "Support"
}, {
    "Id": 19,
    "FirstName": "Anthony",
    "LastName": "Remmen",
    "Prefix": "Mr.",
    "Title": "Support Assistant",
    "City": "San Pedro",
    "Phone": "(310) 555-6625",
    "Email": "anthonyr@dx-email.com",
    "BirthDate": "1986-02-19 00:00:00",
    "Department": "Support"
}, {
    "Id": 20,
    "FirstName": "Olivia",
    "LastName": "Peyton",
    "Prefix": "Mrs.",
    "Title": "Sales Assistant",
    "City": "San Pedro",
    "Phone": "(310) 555-2728",
    "Email": "oliviap@dx-email.com",
    "BirthDate": "1981-06-03 00:00:00",
    "Department": "Sales"
}, {
    "Id": 21,
    "FirstName": "Taylor",
    "LastName": "Riley",
    "Prefix": "Mr.",
    "Title": "Network Admin",
    "City": "West Hollywood",
    "Phone": "(310) 555-7276",
    "Email": "taylorr@dx-email.com",
    "BirthDate": "1982-08-14 00:00:00",
    "Department": "IT"
}, {
    "Id": 22,
    "FirstName": "Amelia",
    "LastName": "Harper",
    "Prefix": "Mrs.",
    "Title": "Network Admin",
    "City": "Los Angeles",
    "Phone": "(213) 555-4276",
    "Email": "ameliah@dx-email.com",
    "BirthDate": "1983-11-19 00:00:00",
    "Department": "IT"
}, {
    "Id": 23,
    "FirstName": "Walter",
    "LastName": "Hobbs",
    "Prefix": "Mr.",
    "Title": "Programmer",
    "City": "Chatsworth",
    "Phone": "(818) 555-8872",
    "Email": "wallyh@dx-email.com",
    "BirthDate": "1984-12-24 00:00:00",
    "Department": "IT"
}, {
    "Id": 24,
    "FirstName": "Bradley",
    "LastName": "Jameson",
    "Prefix": "Mr.",
    "Title": "Programmer",
    "City": "San Fernando",
    "Phone": "(818) 555-4646",
    "Email": "bradleyj@dx-email.com",
    "BirthDate": "1988-10-12 00:00:00",
    "Department": "IT"
}, {
    "Id": 25,
    "FirstName": "Karen",
    "LastName": "Goodson",
    "Prefix": "Miss",
    "Title": "Programmer",
    "City": "South Pasadena",
    "Phone": "(626) 555-0908",
    "Email": "kareng@dx-email.com",
    "BirthDate": "1987-04-26 00:00:00",
    "Department": "IT"
}, {
    "Id": 26,
    "FirstName": "Marcus",
    "LastName": "Orbison",
    "Prefix": "Mr.",
    "Title": "Travel Coordinator",
    "City": "Los Angeles",
    "Phone": "(213) 555-7098",
    "Email": "marcuso@dx-email.com",
    "BirthDate": "1982-03-02 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 27,
    "FirstName": "Sandra",
    "LastName": "Bright",
    "Prefix": "Ms.",
    "Title": "Benefits Coordinator",
    "City": "Tujunga",
    "Phone": "(818) 555-0524",
    "Email": "sandrab@dx-email.com",
    "BirthDate": "1983-09-11 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 28,
    "FirstName": "Morgan",
    "LastName": "Kennedy",
    "Prefix": "Mrs.",
    "Title": "Graphic Designer",
    "City": "San Fernando Valley",
    "Phone": "(818) 555-8238",
    "Email": "morgank@dx-email.com",
    "BirthDate": "1984-07-17 00:00:00",
    "Department": "IT"
}, {
    "Id": 29,
    "FirstName": "Violet",
    "LastName": "Bailey",
    "Prefix": "Ms.",
    "Title": "Jr Graphic Designer",
    "City": "La Canada",
    "Phone": "(818) 555-2478",
    "Email": "violetb@dx-email.com",
    "BirthDate": "1985-06-10 00:00:00",
    "Department": "IT"
}, {
    "Id": 30,
    "FirstName": "Kent",
    "LastName": "Samuelson",
    "Prefix": "Dr.",
    "Title": "Ombudsman",
    "City": "Santa Fe Springs",
    "Phone": "(562) 555-9282",
    "Email": "kents@dx-email.com",
    "BirthDate": "1972-09-11 00:00:00",
    "Department": "Human Resources"
}, {
    "Id": 31,
    "FirstName": "Natalie",
    "LastName": "Maguirre",
    "Prefix": "Mrs.",
    "Title": "Trainer",
    "City": "Long Beach",
    "Phone": "(562) 555-8377",
    "Email": "nataliem@dx-email.com",
    "BirthDate": "1977-10-07 00:00:00",
    "Department": "Support"
}, {
    "Id": 32,
    "FirstName": "Bart",
    "LastName": "Arnaz",
    "Prefix": "Mr.",
    "Title": "Director of Engineering",
    "City": "Irvine",
    "Phone": "(714) 555-2000",
    "Email": "barta@dx-email.com",
    "BirthDate": "1979-11-01 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 33,
    "FirstName": "Leah",
    "LastName": "Simpson",
    "Prefix": "Mrs.",
    "Title": "Test Coordinator",
    "City": "Whittier",
    "Phone": "(562) 559-5830",
    "Email": "leahs@dx-email.com",
    "BirthDate": "1983-04-19 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 34,
    "FirstName": "Arnold",
    "LastName": "Schwartz",
    "Prefix": "Mr.",
    "Title": "Engineer",
    "City": "Brea",
    "Phone": "(714) 555-8882",
    "Email": "arnolds@dx-email.com",
    "BirthDate": "1985-02-28 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 35,
    "FirstName": "William",
    "LastName": "Zimmer",
    "Prefix": "Mr.",
    "Title": "Engineer",
    "City": "Redlands",
    "Phone": "(909) 555-6939",
    "Email": "williamz@dx-email.com",
    "BirthDate": "1986-06-16 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 36,
    "FirstName": "Samantha",
    "LastName": "Piper",
    "Prefix": "Ms.",
    "Title": "Engineer",
    "City": "Los Angeles",
    "Phone": "(323) 555-4512",
    "Email": "samanthap@dx-email.com",
    "BirthDate": "1984-12-01 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 37,
    "FirstName": "Margaret",
    "LastName": "Boxter",
    "Prefix": "Mrs.",
    "Title": "Engineer",
    "City": "Santa Ana",
    "Phone": "(714) 555-7239",
    "Email": "margaretb@dx-email.com",
    "BirthDate": "1987-11-22 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 38,
    "FirstName": "Terry",
    "LastName": "Bradley",
    "Prefix": "Mr.",
    "Title": "QA Engineer",
    "City": "Simi Valley",
    "Phone": "(805) 555-2788",
    "Email": "terryb@dx-email.com",
    "BirthDate": "1984-01-09 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 39,
    "FirstName": "Gabriel",
    "LastName": "Jones",
    "Prefix": "Mr.",
    "Title": "Retail Coordinator",
    "City": "Beverly Hills",
    "Phone": "(310) 555-5395",
    "Email": "gabrielj@dx-email.com",
    "BirthDate": "1987-12-29 00:00:00",
    "Department": "Support"
}, {
    "Id": 40,
    "FirstName": "Lucy",
    "LastName": "Ball",
    "Prefix": "Ms.",
    "Title": "Sales Assistant",
    "City": "Pacific Palisades",
    "Phone": "(310) 555-3357",
    "Email": "lucyb@dx-email.com",
    "BirthDate": "1986-08-09 00:00:00",
    "Department": "Sales"
}, {
    "Id": 41,
    "FirstName": "James",
    "LastName": "Packard",
    "Prefix": "Mr.",
    "Title": "Retail Sales Manager",
    "City": "Bakersfield",
    "Phone": "(661) 555-8224",
    "Email": "jamesp@dx-email.com",
    "BirthDate": "1985-06-22 00:00:00",
    "Department": "Sales"
}, {
    "Id": 42,
    "FirstName": "Hannah",
    "LastName": "Brooklyn",
    "Prefix": "Mrs.",
    "Title": "Online Sales Manager",
    "City": "San Luis Obispo",
    "Phone": "(805) 555-3627",
    "Email": "hannahb@dx-email.com",
    "BirthDate": "1984-07-02 00:00:00",
    "Department": "Sales"
}, {
    "Id": 43,
    "FirstName": "Harvey",
    "LastName": "Mudd",
    "Prefix": "Mr.",
    "Title": "Retail Sales Manager",
    "City": "Monterey",
    "Phone": "(831) 555-3895",
    "Email": "harveym@dx-email.com",
    "BirthDate": "1989-05-11 00:00:00",
    "Department": "Sales"
}, {
    "Id": 44,
    "FirstName": "Clark",
    "LastName": "Morgan",
    "Prefix": "Mr.",
    "Title": "Retail Sales Manager",
    "City": "Martinez",
    "Phone": "(925) 555-2525",
    "Email": "clarkm@dx-email.com",
    "BirthDate": "1988-04-07 00:00:00",
    "Department": "Sales"
}, {
    "Id": 45,
    "FirstName": "Todd",
    "LastName": "Hoffman",
    "Prefix": "Mr.",
    "Title": "Retail Sales Manager",
    "City": "Livermore",
    "Phone": "(925) 555-3579",
    "Email": "toddh@dx-email.com",
    "BirthDate": "1987-03-25 00:00:00",
    "Department": "Sales"
}, {
    "Id": 46,
    "FirstName": "Jack",
    "LastName": "Garmin",
    "Prefix": "Mr.",
    "Title": "Support Assistant",
    "City": "Los Angeles",
    "Phone": "(213) 555-1824",
    "Email": "jackg@dx-email.com",
    "BirthDate": "1988-09-11 00:00:00",
    "Department": "Support"
}, {
    "Id": 47,
    "FirstName": "Lincoln",
    "LastName": "Bartlett",
    "Prefix": "Mr.",
    "Title": "Sales Assistant",
    "City": "Los Angeles",
    "Phone": "(213) 555-8272",
    "Email": "lincolnb@dx-email.com",
    "BirthDate": "1990-08-02 00:00:00",
    "Department": "Sales"
}, {
    "Id": 48,
    "FirstName": "Brad",
    "LastName": "Farkus",
    "Prefix": "Mr.",
    "Title": "Engineer",
    "City": "Los Angeles",
    "Phone": "(213) 555-3626",
    "Email": "bradf@dx-email.com",
    "BirthDate": "1991-03-17 00:00:00",
    "Department": "Engineering"
}, {
    "Id": 49,
    "FirstName": "Jennifer",
    "LastName": "Hobbs",
    "Prefix": "Ms.",
    "Title": "Shipping Assistant",
    "City": "Los Angeles",
    "Phone": "(310) 555-2668",
    "Email": "jennyh@dx-email.com",
    "BirthDate": "1992-07-14 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 50,
    "FirstName": "Dallas",
    "LastName": "Lou",
    "Prefix": "Mr.",
    "Title": "Shipping Assistant",
    "City": "Los Angeles",
    "Phone": "(213) 555-8357",
    "Email": "dallas@dx-email.com",
    "BirthDate": "1994-08-19 00:00:00",
    "Department": "Shipping"
}, {
    "Id": 51,
    "FirstName": "Stu",
    "LastName": "Pizaro",
    "Prefix": "Mr.",
    "Title": "Engineer",
    "City": "Los Angeles",
    "Phone": "(213) 555-2552",
    "Email": "stu@dx-email.com",
    "BirthDate": "1985-09-11 00:00:00",
    "Department": "Engineering"
}];