var employees = [
    {
        "ID": 1,
        "First_Name": "John",
        "Last_Name": "Heart",
        "Full_Name": "John Heart",
        "Prefix": "Mr.",
        "Title": "CEO",
        "Picture": "/Content/images/doc/16_2/UiWidgets/FormTutorialData/1.png",
        "Address": "351 S Hill St.",
        "City": "Los Angeles",
        "State_ID": 5,
        "Zipcode": 90013,
        "Email": "jheart@dx-email.com",
        "Skype": "jheart_DX_skype",
        "Mobile_Phone": "(213) 555-9392",
        "Home_Phone": "(213) 555-9208",
        "Birth_Date": "1964-03-16T00:00:00",
        "Hire_Date": "1995-01-15T00:00:00",
        "Department_ID": 6,
        "Status": "Salaried",
        "Personal_Profile": "John has been in the Audio/Video industry since 1990. He has led DevAv as its CEO since 2003.\r\n\r\nWhen not working hard as the CEO, John loves to golf and bowl. He once bowled a perfect game of 300.",
        "Probation_Reason": null,
        "SSMA_TimeStamp": "AAAAAAAAE4k="
    },
    {
        "ID": 2,
        "First_Name": "Samantha",
        "Last_Name": "Bright",
        "Full_Name": "Samantha Bright",
        "Prefix": "Dr.",
        "Title": "COO",
        "Picture": "/Content/images/doc/16_2/UiWidgets/FormTutorialData/2.png",
        "Address": "5801 Wilshire Blvd.",
        "City": "Los Angeles",
        "State_ID": 5,
        "Zipcode": 90036,
        "Email": "samanthab@dx-email.com",
        "Skype": "samanthab_DX_skype",
        "Mobile_Phone": "(213) 555-2858",
        "Home_Phone": "(213) 555-0288",
        "Birth_Date": "1966-05-02T00:00:00",
        "Hire_Date": "2004-05-24T00:00:00",
        "Department_ID": 6,
        "Status": "Salaried",
        "Personal_Profile": "Samantha has been DevAV's COO since 2009. She is a proud mom of 3 boys and 1 girl. \r\n\r\nWhen not working hard as our Operations Manager, she volunteers her time with the American Red Cross.",
        "Probation_Reason": null,
        "SSMA_TimeStamp": "AAAAAAAAE4o="
    },
    {
        "ID": 3,
        "First_Name": "Arthur",
        "Last_Name": "Miller",
        "Full_Name": "Arthur Miller",
        "Prefix": "Mr.",
        "Title": "CTO",
        "Picture": "/Content/images/doc/16_2/UiWidgets/FormTutorialData/3.png",
        "Address": "3800 Homer St.",
        "City": "Los Angeles",
        "State_ID": 5,
        "Zipcode": 90031,
        "Email": "arthurm@dx-email.com",
        "Skype": "arthurm_DX_skype",
        "Mobile_Phone": "(310) 555-8583",
        "Home_Phone": "(310) 555-6542",
        "Birth_Date": "1972-07-11T00:00:00",
        "Hire_Date": "2007-12-18T00:00:00",
        "Department_ID": 6,
        "Status": "Salaried",
        "Personal_Profile": "Arthur has been a prominent figure in the AV industry for decades. His love for technology is unmatched.\r\n\r\nIn his free time, Arthur races cars and jumps out of airplanes (with a parachute).",
        "Probation_Reason": null,
        "SSMA_TimeStamp": "AAAAAAAAE4s="
    }
];